# Use root/example as user/password credentials
version: '3.3'
networks:
  b2w_network:
#    external: true

services:

  dbb2w:
    build:
      dockerfile: DockerfileDB
      context: ./
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_example
      MYSQL_USER: b2w
      MYSQL_PASSWORD: b2w
    ports:
      - 3306:3306
    networks:
      - b2w_network


  apib2w:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 8080:8080


